name: convert_simple_3d
description: A project for converting between simple_3d objects and other 3d formats.
version: 0.0.2
repository: https://github.com/MasahideMori-SimpleAppli/convert_simple_3d

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^13.1.1
  simple_3d_renderer: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
